<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-C8GDP60" failures="1" tests="9" name="PersonalLoan" time="0.116" errors="0" timestamp="11 Sep 2020 00:22:02 GMT">
  <testcase classname="test.day1" name="lasTTest" time="0.027">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.lasTTest(day1.java:18)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- lasTTest -->
  <testcase classname="test.day1" name="secondTest" time="0.002"/>
  <testcase classname="test.day3" name="AWeblogin" time="0.002"/>
  <testcase classname="test.day3" name="Mobilesignout" time="0.007"/>
  <testcase classname="test.day3" name="Mobilesignout" time="0.002"/>
  <testcase classname="test.day3" name="Mobilesignout" time="0.001"/>
  <testcase classname="test.day3" name="WebloginURL" time="0.002"/>
  <testcase classname="test.day3" name="mobileLogin" time="0.001"/>
  <testcase classname="test.day3" name="APIcarloan" time="0.001"/>
  <testcase classname="test.day3" name="Weblogin" time="0.0">
    <ignored/>
  </testcase> <!-- Weblogin -->
</testsuite> <!-- PersonalLoan -->
